### ISSUE TITLE
dest_ip is set to src_ip

### ISSUE THREAD

**Issue by dfronck** [inspired/TA-cisco_firepower#1]
First, thanks for this. You saved me a ton of time.

dest_ip is set to SrcIP in TA-cisco_firepower-master/default/transforms.conf
# CIM: Network Traffic DM
[extract_cisco_firepower_dest_ip]
SOURCE_KEY = message_text
REGEX = SrcIP: (?<dest_ip>\S+),

Regex should be 
REGEX = DstIP: (?<dest_ip>\S+),

**Comment by inspired** [comment]
Thanks. Fixed in 00edcfd
